### ISSUE TITLE
Size of input elements on mobile is hardcoded to pixels.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/AleyDafna-Shop#21]
![screenshot from 2016-05-01 12-10-45](https://cloud.githubusercontent.com/assets/1911594/14941001/d06c516c-0f95-11e6-83a8-83adec87c1ce.png)
Resulting is a bad behavior on different aspect rations of phones. Style being set is this:

``` css
div#input_details label input,
div#payment_method input,
div#billing_information input,
div#input_details div.existing_account.visible input,
div#input_details div.new_account.visible input,
div#input_details div.guest_checkout.visible input,
div#checkout_container div.page input {
    width: 280px;
    padding: 10px;
    border: 1px solid #75cb1d;
    border-radius: 0px 0px 0px 0px;
    background-color: #ecf0f1;
    color: #34495e;
    transition: all 0.3s;
}
```

Width needs to be either in `%` or left alone for browser to decide. I recommend the former.
